name: 'lvh-run'
description: 'Runs LVH VMs for Cilium CI testing'
inputs:
  test-name:
    description: 'Unique test name'
    required: true
  image:
    description: 'LVH image name ("base", "kind", etc)'
    required: true
    default: 'kind'
  image-version:
    description: 'LVH image version'
    required: true
    default: '5.10-main'
  images-folder-parent:
    description: 'Parent folder in which to put the downloaded images'
    required: false
    default: ''
  lvh-version:
    description: 'LVH cli version (Docker tag)'
    required: true
    default: 'v0.0.23'
  cmd:
    description: 'Commands to run in a VM (any occurance of "$" within "cmd" must be escaped)'
    required: true
  ssh-port:
    description: 'SSH port for VM on a host'
    required: true
    default: '2222'
  ssh-connect-wait-retries:
    description: 'Number of retries to connect to the SSH server'
    required: true
    default: '300'
  ssh-connect-wait-timeout:
    description: 'Timeout in seconds between retries to connect to the SSH server'
    required: true
    default: '1'
  host-mount:
    description: 'Host dir path to mount in /host dir of a VM'
    required: true
  provision:
    description: 'Provision VM (if set to false, only given test cmd is going to be run)'
    required: true
    default: 'true'
  install-dependencies:
    description: 'Install QEMU dependencies (Debian/Ubuntu)'
    default: 'false'
  serial-port:
    description: 'Serial port to access VM'
    required: true
    default: '0'
  cpu:
    description: 'CPU count'
    required: false
  mem:
    description: 'RAM size'
    required: false
  cpu-kind:
    description: 'CPU kind to use'
    required: true
    default: 'host'
  kernel-path:
    description: 'Path to kernel image to boot with'
    required: false
  verbose:
    description: 'Run in verbose mode'
    required: true
    default: 'false'
  port-forward:
    description: 'Additional to SSH comma-separated port forwards ($LOCAL:$VM_PORT)'
    required: false
  arch:
    description: 'VM architecture (amd64 (default) or arm64)'
    default: 'amd64'
    required: false
  kernel-version:
    description: 'Kernel version (if empty, a kernel from the image will be used)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Find LVH cli
      if: ${{ inputs.provision == 'true' }}
      id: find-lvh-cli
      shell: bash
      run: |
        if command -v lvh 2>&1 >/dev/null; then
          echo 'skip=true' >> $GITHUB_OUTPUT
        fi
        runner_os_id=$(grep VERSION_ID /etc/os-release | cut -d= -f 2 | sed 's/"//g')
        echo "runner_os_id=${runner_os_id}" >> $GITHUB_OUTPUT

        dependencies="qemu-system cpu-checker libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager"
        if [[ "${{ inputs.arch }}" == "amd64" ]]; then
          dependencies="qemu-system-x86 ${dependencies}"
        elif [[ "${{ inputs.arch }}" == "arm64" ]]; then
          dependencies="qemu-system-arm ${dependencies}"
        else
          echo "Unsupported arch ${{ inputs.arch }}"
          exit 1
        fi
        echo "dependency_list=${dependencies}" >> $GITHUB_OUTPUT

        dependencies_sha=$(echo ${dependencies} | md5sum)
        echo "dependency_list_sha=${dependencies_sha}" >> $GITHUB_OUTPUT

    - name: Install LVH cli
      if: ${{ inputs.provision == 'true' && steps.find-lvh-cli.outputs.skip != 'true' }}
      shell: bash
      run: |
        cid=$(docker create quay.io/lvh-images/lvh:${{ inputs.lvh-version }})
        docker cp $cid:/usr/bin/lvh /tmp/lvh
        docker rm $cid
        chmod +x /tmp/lvh
        sudo mv /tmp/lvh /bin/lvh

    - name: Load install packages from GitHub cache
      if: ${{ inputs.provision == 'true' && inputs.install-dependencies == 'true' }}
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      id: package-cache
      with:
        path: /tmp/.ubuntu-pkgs
        key: ${{ runner.os }}-${{ steps.find-lvh-cli.outputs.runner_os_id }}-pkgs-cilium-little-vm-helper-${{ steps.find-lvh-cli.outputs.dependency_list_sha }}

    - name: Download LVH dependencies
      if: ${{ inputs.provision == 'true' && inputs.install-dependencies == 'true' && steps.package-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        n=0
        until [ "$n" -ge 5 ]; do
          success=1
          sudo apt update && \
          sudo apt-get clean && \
          sudo apt-get -d -y --no-install-recommends install ${{steps.find-lvh-cli.outputs.dependency_list}} && \
          break || success=0
          n=$((n+1))
          sleep 1
        done
        [ $success -eq 1 ] || exit 42
        sudo mkdir -p /tmp/.ubuntu-pkgs
        sudo cp /var/cache/apt/archives/*.deb /tmp/.ubuntu-pkgs

    - name: Install dependencies
      if: ${{ inputs.provision == 'true' && inputs.install-dependencies == 'true' }}
      shell: bash
      run: |
        # Disable auto update of man-db for every package
        sudo rm /var/lib/man-db/auto-update
        sudo cp /tmp/.ubuntu-pkgs/*.deb /var/cache/apt/archives/
        sudo apt-get -y --no-install-recommends install /tmp/.ubuntu-pkgs/*.deb
        sudo kvm-ok

    - name: Derive VM image file name
      if: ${{ inputs.provision == 'true' }}
      id: derive-image-name
      shell: bash
      run: echo "image-name=$(echo ${{ inputs.image }} | sed 's/\-ci//g')_$(echo ${{ inputs.image-version }} | sed 's/^\(.*\)\-[0-9.]*\(\-[^-]*\)*\(@sha256:.*\)*$/\1/g')" >> $GITHUB_OUTPUT

    - name: Create dirs for image and kernel
      shell: bash
      run: |
        # chmod dirs so that the cache hits can decompress the artifacts
        sudo mkdir -p ${{ inputs.images-folder-parent }}/kernels/${{ inputs.arch }}/
        sudo chmod -R 777 ${{ inputs.images-folder-parent }}/kernels/${{ inputs.arch }}/
        sudo mkdir -p ${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}/images
        sudo chmod -R 777 ${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}/images

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: ${{ inputs.provision == 'true' }}
      id: cache-lvh-image
      with:
        path: ${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}/images/${{ steps.derive-image-name.outputs.image-name }}.qcow2.zst
        key: lvh-image-${{ inputs.image }}_${{ inputs.image-version }}_${{ inputs.arch }}

    - name: Decompressed cached VM image
      if: ${{ inputs.provision == 'true' && steps.cache-lvh-image.outputs.cache-hit == 'true' }}
      shell: bash
      run: zstd -df ${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}/images/${{ steps.derive-image-name.outputs.image-name }}.qcow2.zst

    - name: Fetch VM image
      if: ${{ inputs.provision == 'true' && steps.cache-lvh-image.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        /bin/lvh images pull --platform linux/${{ inputs.arch}} --cache quay.io/lvh-images/${{ inputs.image }}:${{ inputs.image-version }} --dir "${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}/"
        find ${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}/ -type f -exec sudo chmod 666 {} +
        find ${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: ${{ inputs.provision == 'true' && inputs.kernel-version != '' }}
      id: cache-lvh-kernel
      with:
        path: ${{ inputs.images-folder-parent }}/kernels/${{ inputs.arch }}/${{ inputs.kernel-version }}
        key: lvh-kernel-${{ inputs.kernel-version }}_${{ inputs.arch }}

    - name: Fetch kernel
      id: fetch-kernel
      if: ${{ inputs.provision == 'true' && inputs.kernel-version != '' && steps.cache-lvh-kernel.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        /bin/lvh kernel pull --platform=linux/${{ inputs.arch }} --dir "${{ inputs.images-folder-parent }}/kernels/${{ inputs.arch }}" ${{ inputs.kernel-version }}

    - name: Set kernel path
      id: kernel-path
      shell: bash
      run: |
        echo lvh_kernel_path=$(find ${{ inputs.images-folder-parent }}/kernels/${{ inputs.arch }}/${{ inputs.kernel-version }}/boot/ -name "vmlinuz-*" -type f | head -1) >> "$GITHUB_OUTPUT"

    - name: Start VM
      if: ${{ inputs.provision == 'true' }}
      shell: bash
      run: |
        extraArgs=()
        if [ ! -z "${{ inputs.kernel-path }}" ]; then
          extraArgs+=("--kernel" "${{ inputs.kernel-path }}")
        fi
        if [ "${{ steps.kernel-path.outputs.lvh_kernel_path }}" != "" ]; then
          extraArgs+=("--kernel ${{ steps.kernel-path.outputs.lvh_kernel_path }}")
        fi
        if [ "${{ inputs.verbose }}" == "true" ]; then
          extraArgs+=("--verbose")
        fi
        if [ "${{ inputs.port-forward }}" != "" ]; then
          fwds=($(echo "${{ inputs.port-forward }}" | tr "," "\n"))
          for fwd in "${fwds[@]}"; do
            extraArgs+=("-p" "$fwd")
          done
        fi
        if [ ! -z "${{ inputs.cpu-kind }}" ]; then
          extraArgs+=("--cpu-kind" "${{ inputs.cpu-kind }}")
        fi

        sudo touch /tmp/console.log
        # Determine the amount of cpu and memory to allocate
        CPU=${{ inputs.cpu }}
        if [ -z "$CPU" ]; then
          CPU=$(nproc)
          echo "cpu unspecified, defaulting to nprocs CPUs: $CPU"
        fi
        MEM=${{ inputs.mem }}
        if [ -z "$MEM" ]; then
          # Default to 75% of the host memory
          MEM="$(free -m | awk '/^Mem:/{print int($2 * 0.75)}')M"
          echo "mem unspecified, defaulting ot 75% of host memory: $MEM"
        fi
        sudo /bin/lvh run --host-mount=${{ inputs.host-mount }} --image ${{ inputs.images-folder-parent }}/images/${{ inputs.arch }}/images/${{ steps.derive-image-name.outputs.image-name }}.qcow2 \
            --daemonize -p ${{ inputs.ssh-port }}:22 --serial-port ${{ inputs.serial-port }} \
            --cpu=$CPU --mem=$MEM \
            --console-log-file /tmp/console.log \
            --qemu-arch ${{ inputs.arch }} \
            ${extraArgs[@]}

    - name: Wait for VM's SSH Server
      if: ${{ inputs.provision == 'true' }}
      shell: bash
      run: |
        n=0
        success=0
        until [ "$n" -ge ${{ inputs.ssh-connect-wait-retries }} ]; do
          if ssh -p ${{ inputs.ssh-port }} -o "StrictHostKeyChecking=no" root@localhost exit; then
            success=1
            break
          fi
          n=$((n+1))
          sleep ${{ inputs.ssh-connect-wait-timeout }}
        done
        if [ $success -eq 0 ]; then
          cat /tmp/console.log
          exit 42
        fi

    - name: Run test cmd in VM
      shell: bash
      run: |
        ssh -p ${{ inputs.ssh-port }} -o "StrictHostKeyChecking=no" root@localhost << EOF
        set -eu

        ${{ inputs.cmd }}
        EOF
