name: build and run unit tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
    - name: Install Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        # renovate: datasource=golang-version depName=go
        go-version: 1.18.4

    - name: Checkout code
      uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3
      with:
        path: src/little-vm-helper

    - name: Build and run Go tests
      run: |
        cd src/little-vm-helper
        make
