name: build and run unit tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.4'

    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        path: src/little-vm-helper

    - name: Build and run Go tests
      env:
        GOPATH: /home/runner/work/tetragon/tetragon/go
      run: |
        cd src/little-vm-helper
        make
