name: build and run unit tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18.4'

    - name: Checkout code
      uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      with:
        path: src/little-vm-helper

    - name: Build and run Go tests
      env:
        GOPATH: /home/runner/work/tetragon/tetragon/go
      run: |
        cd src/little-vm-helper
        make
