name: build and run unit tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        path: src/little-vm-helper

    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: "src/little-vm-helper/go.mod"

    - name: Build and run Go tests
      run: |
        cd src/little-vm-helper
        make
