name: build and run unit tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: src/little-vm-helper

    - name: Install Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: "src/little-vm-helper/go.mod"

    - name: Build and run Go tests
      run: |
        cd src/little-vm-helper
        make
